/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hasan
 */
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class KargoGonder extends javax.swing.JFrame {

    /**
     * Creates new form KargoGonder
     */
    DefaultTableModel dtm = new DefaultTableModel();
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:MM:SS");
    int id;
    public KargoGonder() {
        initComponents();
        Seticon();
        this.setLocationRelativeTo(null);
        super.getContentPane().setBackground(Color.PINK);
        bttnIdIcın.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGönderenAdı = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NetAgirlik = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        txtGönderenAdres = new javax.swing.JTextField();
        txtGönderenTel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGönderenTc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateChooserCombo3 = new datechooser.beans.DateChooserCombo();
        jSlider1 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtAlıcıTel = new javax.swing.JTextField();
        rbYurtIci = new javax.swing.JRadioButton();
        UcretGör = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlıcıNot = new javax.swing.JTextArea();
        txtAlıcıSoyad = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bttnIdIcın = new javax.swing.JButton();
        txtAlıcıAd = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGönderenSoyad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAlıcıAdres = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnKaydet = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtalıcıtc = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        rbYurtDisi = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        MinIcon = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Exitİcon = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGönderenAdı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGönderenAdıActionPerformed(evt);
            }
        });
        getContentPane().add(txtGönderenAdı, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 194, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("NET AĞIRLIK : ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("AD :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("AD :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 33, -1));
        getContentPane().add(NetAgirlik, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 630, 207, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ", "NORMAL", "KIRILACAK", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 207, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel19.setText("ÜCRET BİLGİSİ :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, -1, -1));
        getContentPane().add(txtGönderenAdres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 198, 61));
        getContentPane().add(txtGönderenTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 194, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ALICI BİLGİLERİ :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 170, 33));
        getContentPane().add(txtGönderenTc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 194, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("KARGO TÜRÜ :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("ADRES :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        dateChooserCombo3.setCalendarBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(dateChooserCombo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 180, 31));

        jSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jSlider1.setForeground(new java.awt.Color(255, 0, 51));
        jSlider1.setMaximum(1000);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSlider1MouseClicked(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 207, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("TARİH :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("AĞIRLIK :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));
        getContentPane().add(txtAlıcıTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 203, 31));

        rbYurtIci.setBackground(new java.awt.Color(255, 255, 255));
        rbYurtIci.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbYurtIci.setText("YURT İÇİ KARGO");
        rbYurtIci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbYurtIciActionPerformed(evt);
            }
        });
        getContentPane().add(rbYurtIci, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 150, -1));
        getContentPane().add(UcretGör, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 740, 208, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("TELEFON NO :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtAlıcıNot.setColumns(20);
        txtAlıcıNot.setRows(5);
        jScrollPane2.setViewportView(txtAlıcıNot);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 203, 90));
        getContentPane().add(txtAlıcıSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 203, 29));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ", "KAPIDA ÖDEME ", "ONLİNE ÖDEME", " " }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 207, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("SOYAD :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("NOT :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, 34));

        bttnIdIcın.setBackground(new java.awt.Color(102, 204, 255));
        bttnIdIcın.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttnIdIcın.setText("KARGO ID ÖĞREN ");
        bttnIdIcın.setAutoscrolls(true);
        bttnIdIcın.setDoubleBuffered(true);
        bttnIdIcın.setFocusCycleRoot(true);
        bttnIdIcın.setFocusTraversalPolicy(null);
        bttnIdIcın.setFocusTraversalPolicyProvider(true);
        bttnIdIcın.setHideActionText(true);
        bttnIdIcın.setInheritsPopupMenu(true);
        bttnIdIcın.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnIdIcınActionPerformed(evt);
            }
        });
        getContentPane().add(bttnIdIcın, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, 190, 47));
        getContentPane().add(txtAlıcıAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 203, 28));

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setText("ÜCRET İÇİN TIKLA ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 680, 208, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("GÖNDERİCİ BİLGİSİ :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, 33));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("T.C.  ID :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        getContentPane().add(txtGönderenSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 194, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("ADRES :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, 26));
        getContentPane().add(txtAlıcıAdres, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 203, 54));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("ÖDEME TÜRÜ : ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("T.C. ID :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("TELEFON NO :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        btnKaydet.setBackground(new java.awt.Color(102, 204, 255));
        btnKaydet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKaydet.setText("KAYDET");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btnKaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 190, 47));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("SOYAD :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));
        getContentPane().add(txtalıcıtc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 203, 29));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel20.setText("ÖDENECEK TUTAR :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, -1, -1));

        rbYurtDisi.setBackground(new java.awt.Color(255, 255, 255));
        rbYurtDisi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbYurtDisi.setText("YURT DIŞI KARGO");
        rbYurtDisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbYurtDisiActionPerformed(evt);
            }
        });
        getContentPane().add(rbYurtDisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 150, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("91 EXPRESS KARGO GÖNDERME PANELİ ");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 42));

        MinIcon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel22.setText("-");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MinIconLayout = new javax.swing.GroupLayout(MinIcon);
        MinIcon.setLayout(MinIconLayout);
        MinIconLayout.setHorizontalGroup(
            MinIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MinIconLayout.setVerticalGroup(
            MinIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MinIconLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(MinIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, 44));

        jPanel8.setBackground(new java.awt.Color(255, 0, 0));

        Exitİcon.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Exitİcon.setForeground(new java.awt.Color(255, 255, 255));
        Exitİcon.setText("X");
        Exitİcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitİconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Exitİcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Exitİcon, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        btn_Back.setBackground(new java.awt.Color(25, 181, 254));
        btn_Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Back.setText("<--");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(dateChooserCombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 740, 190, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gokyuzuicon.jpg"))); // NOI18N
        jLabel23.setText("jLabel23");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 780, 820));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged

        NetAgirlik.setText(String.valueOf(jSlider1.getValue() + ""));
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1MouseClicked

    private void rbYurtIciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbYurtIciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbYurtIciActionPerformed

    private void bttnIdIcınActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnIdIcınActionPerformed

        MüsteriId mı=new MüsteriId(id);
        mı.setVisible(true);
    }//GEN-LAST:event_bttnIdIcınActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Kargo k = new Kargo();

        if (rbYurtIci.isSelected()) {

            if (jSlider1.getValue() >= 0 && jSlider1.getValue() <= 50) {
                UcretGör.setText("50 TL");
            } else if (jSlider1.getValue() > 50 && jSlider1.getValue() <= 200) {
                UcretGör.setText("150 TL");
            } else if (jSlider1.getValue() > 200 && jSlider1.getValue() <= 500) {
                UcretGör.setText("350 TL");
            } else if (jSlider1.getValue() > 500 && jSlider1.getValue() <= 800) {
                UcretGör.setText("650 TL");
            } else if (jSlider1.getValue() > 800 && jSlider1.getValue() <= 1000) {
                UcretGör.setText("900 TL");
            }
        } else if (rbYurtDisi.isSelected()) {

            YurtDisi yd = new YurtDisi();

            if (jSlider1.getValue() >= 0 && jSlider1.getValue() <= 50) {
                UcretGör.setText("500 TL");

            } else if (jSlider1.getValue() > 50 && jSlider1.getValue() <= 200) {
                UcretGör.setText("1500 TL");

            } else if (jSlider1.getValue() > 200 && jSlider1.getValue() <= 500) {
                UcretGör.setText("3500 TL");

            } else if (jSlider1.getValue() > 500 && jSlider1.getValue() <= 800) {
                UcretGör.setText("6500 TL");

            } else if (jSlider1.getValue() > 800 && jSlider1.getValue() <= 1000) {
                UcretGör.setText("9000 TL");

            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed

        try {
            // TODO add your handling code here:

            JOptionPane.showMessageDialog(this, "Kargonuz kaydedildi.Id numaranızı öğrenmek için diğer butona tıklayınız. ");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            String sql = "INSERT INTO alankısı (tc,ad,soyad,tel,adres) VALUES(?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, (txtalıcıtc.getText()));
            ps.setString(2, txtAlıcıAd.getText());
            ps.setString(3, txtAlıcıSoyad.getText());
            ps.setString(4, txtAlıcıTel.getText());
            ps.setString(5, txtAlıcıAdres.getText());

            ps.executeUpdate();

            Kargo.kargoId++;

            String sql1="INSERT INTO gonderenkısı (tc,ad,soyad,tel,adres) VALUES (?,?,?,?,?)";
            PreparedStatement ps1 = con.prepareStatement(sql1);
            ps1.setString(1, txtGönderenTc.getText());
            ps1.setString(2, txtGönderenAdı.getText());
            ps1.setString(3, txtGönderenSoyad.getText());
            ps1.setString(4, txtGönderenTel.getText());
            ps1.setString(5, txtGönderenAdres.getText());

            ps1.executeUpdate();

            String   sql2="INSERT INTO KARGOLAR  (alanTc,gönderenTc) VALUES (?,?)";
            PreparedStatement  ps2 = con.prepareStatement(sql2);

            ps2.setString(1, txtalıcıtc.getText());
            ps2.setString(2, txtGönderenTc.getText());

            ps2.executeUpdate();

            String sql3= "SELECT KARGOID FROM KARGOLAR WHERE alanTc=? AND gönderenTC=?";
            PreparedStatement ps3= con.prepareStatement(sql3);
            ps3.setString(1, txtalıcıtc.getText());
            ps3.setString(2, txtGönderenTc.getText());

            ResultSet rs1= ps3.executeQuery();
            while(rs1.next()){
                id=rs1.getInt(1);

            }

            txtAlıcıAd.setText(null);
            txtAlıcıSoyad.setText(null);
            txtAlıcıAdres.setText(null);
            txtAlıcıNot.setText(null);
            txtAlıcıTel.setText(null);
            txtGönderenAdres.setText(null);
            txtGönderenAdı.setText(null);
            txtGönderenSoyad.setText(null);
            //  txtGönderenTarih.setText(null);
            txtGönderenTc.setText(null);
            txtGönderenTel.setText(null);
            txtalıcıtc.setText(null);

            bttnIdIcın.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(KargoGonder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void rbYurtDisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbYurtDisiActionPerformed

    }//GEN-LAST:event_rbYurtDisiActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.setState(JFrame.ICONIFIED);//min icon
    }//GEN-LAST:event_jLabel22MouseClicked

    private void ExitİconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitİconMouseClicked
        System.exit(0);//iptal icon
    }//GEN-LAST:event_ExitİconMouseClicked

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        this.setVisible(false);  // register ekranını kapatıyoruz
        new Giriş().setVisible(true);// login ekranını tekrar açıyoruz.
    }//GEN-LAST:event_btn_BackActionPerformed

    private void txtGönderenAdıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGönderenAdıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGönderenAdıActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KargoGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KargoGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KargoGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KargoGonder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KargoGonder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exitİcon;
    private javax.swing.JPanel MinIcon;
    private javax.swing.JTextField NetAgirlik;
    private javax.swing.JTextField UcretGör;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton bttnIdIcın;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private datechooser.beans.DateChooserCombo dateChooserCombo3;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JRadioButton rbYurtDisi;
    private javax.swing.JRadioButton rbYurtIci;
    private javax.swing.JTextField txtAlıcıAd;
    private javax.swing.JTextField txtAlıcıAdres;
    private javax.swing.JTextArea txtAlıcıNot;
    private javax.swing.JTextField txtAlıcıSoyad;
    private javax.swing.JTextField txtAlıcıTel;
    private javax.swing.JTextField txtGönderenAdres;
    private javax.swing.JTextField txtGönderenAdı;
    private javax.swing.JTextField txtGönderenSoyad;
    private javax.swing.JTextField txtGönderenTc;
    private javax.swing.JTextField txtGönderenTel;
    private javax.swing.JTextField txtalıcıtc;
    // End of variables declaration//GEN-END:variables

    private void Seticon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("91siyah.png")));
    }
}
